"""Initial migration

Revision ID: 210709532110
Revises: 
Create Date: 2026-09-26 01:54:29.260027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210709532110'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False, comment="Department name (e.g., 'Sales', 'IT', 'HR')"),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Department description'),
    sa.Column('code', sa.String(length=20), nullable=True, comment="Department code (e.g., 'SALES', 'IT')"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the department is active'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_active', name='uq_dept_code_active')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False, comment="Permission identifier (e.g., 'trainings.read', 'users.create')"),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Human-readable description of the permission'),
    sa.Column('resource', sa.String(length=50), nullable=True, comment="Resource this permission applies to (e.g., 'trainings', 'employees')"),
    sa.Column('action', sa.String(length=20), nullable=True, comment="Action this permission allows (e.g., 'create', 'read', 'update', 'delete')"),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'resource', 'action', name='uq_permission_nra')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment="Role name (e.g., 'super_admin', 'employee')"),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Human-readable description of the role'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this role is active'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'is_active', name='uq_role_name_active')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (used for login)"),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment="User's full name"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Whether this user has super admin privileges'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Hashed password using Argon2'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last login'),
    sa.Column('login_count', sa.Integer(), nullable=False, comment='Number of successful logins'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'is_active', name='uq_user_email_active')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='User ID who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action performed (e.g., 'CREATE_TRAINING', 'UPDATE_EMPLOYEE')"),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment="Entity type affected (e.g., 'TrainingProgram', 'Employee')"),
    sa.Column('resource_id', sa.String(length=36), nullable=True, comment='ID of affected entity'),
    sa.Column('details', sa.JSON(), nullable=True, comment='JSON details of changes or action'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Client IP address'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=20), nullable=False, comment='Unique employee identifier (e.g., EMP-001)'),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment="Employee's first name"),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment="Employee's last name"),
    sa.Column('email', sa.String(length=255), nullable=False, comment="Employee's email address"),
    sa.Column('department_id', sa.String(length=36), nullable=True, comment='Foreign key to department'),
    sa.Column('manager_id', sa.String(length=36), nullable=True, comment='Foreign key to manager employee (self-referential)'),
    sa.Column('designation', sa.String(length=100), nullable=True, comment="Employee's job title/designation"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the employee is active'),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True, comment="Employee's joining date"),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_department_id', 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index('ix_employees_manager_id', 'employees', ['manager_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Foreign key to user'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Notification title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message'),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='Type: Info, Warning, Assignment, Session, Certificate, Completion'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether notification has been read'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='Optional UI link for action'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('training_programs',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Training program title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Training program description'),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Training category (e.g., 'Technical', 'Leadership', 'Compliance')"),
    sa.Column('department_id', sa.String(length=36), nullable=True, comment='Optional department association'),
    sa.Column('trainer_id', sa.String(length=36), nullable=True, comment='Assigned trainer (user ID)'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='Training program start date'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='Training program end date'),
    sa.Column('duration_weeks', sa.Integer(), nullable=True, comment='Duration in weeks'),
    sa.Column('mode', sa.String(length=50), nullable=True, comment="Training mode (e.g., 'online', 'offline', 'hybrid')"),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Training location'),
    sa.Column('max_participants', sa.Integer(), nullable=True, comment='Maximum number of participants'),
    sa.Column('prerequisites', sa.Text(), nullable=True, comment='Prerequisites for the training'),
    sa.Column('learning_objectives', sa.Text(), nullable=True, comment='Learning objectives'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Program status: Draft, Published, Upcoming, In Progress, Completed, Archived'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='Whether this training is mandatory'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_programs_department_id', 'training_programs', ['department_id'], unique=False)
    op.create_index(op.f('ix_training_programs_id'), 'training_programs', ['id'], unique=False)
    op.create_index('ix_training_programs_status', 'training_programs', ['status'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('assignments',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Assignment title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Assignment description and instructions'),
    sa.Column('training_program_id', sa.String(length=36), nullable=False, comment='Foreign key to training program'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Submission due date'),
    sa.Column('max_score', sa.Float(), nullable=False, comment='Maximum possible score'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_index('ix_assignments_training_program_id', 'assignments', ['training_program_id'], unique=False)
    op.create_table('certificates',
    sa.Column('certificate_number', sa.String(length=100), nullable=False, comment='Unique certificate verification number'),
    sa.Column('employee_id', sa.String(length=36), nullable=False, comment='Foreign key to employee'),
    sa.Column('training_program_id', sa.String(length=36), nullable=False, comment='Foreign key to training program'),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False, comment='Date certificate was issued'),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True, comment='Optional expiry date for renewal'),
    sa.Column('issuer_name', sa.String(length=100), nullable=False, comment='Name of issuer'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Path to generated PDF certificate'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_index('ix_certificates_employee_id', 'certificates', ['employee_id'], unique=False)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index('ix_certificates_training_program_id', 'certificates', ['training_program_id'], unique=False)
    op.create_table('courses',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Course title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Course description'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Course order within the training program'),
    sa.Column('estimated_hours', sa.Integer(), nullable=True, comment='Estimated completion hours'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Course status: Draft, Published'),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False, comment='Whether this course is mandatory'),
    sa.Column('training_program_id', sa.String(length=36), nullable=False, comment='Foreign key to training program'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'training_program_id', name='uq_course_title_program')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index('ix_courses_training_program_id', 'courses', ['training_program_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('training_program_id', sa.String(length=36), nullable=False, comment='Foreign key to training program'),
    sa.Column('employee_id', sa.String(length=36), nullable=False, comment='Foreign key to employee'),
    sa.Column('training_rating', sa.Integer(), nullable=False, comment='Rating 1-5 for training program'),
    sa.Column('trainer_rating', sa.Integer(), nullable=False, comment='Rating 1-5 for trainer'),
    sa.Column('material_usefulness', sa.Integer(), nullable=False, comment='Rating 1-5 for materials'),
    sa.Column('difficulty_level', sa.String(length=30), nullable=True, comment='Too Easy, Just Right, Too Hard'),
    sa.Column('confidence_gain', sa.Integer(), nullable=True, comment='Rating 1-5 on confidence improvement'),
    sa.Column('suggestions', sa.Text(), nullable=True, comment='Suggestions for improvement'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_program_id', 'employee_id', name='uq_feedback_program_emp')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index('ix_feedbacks_training_program_id', 'feedbacks', ['training_program_id'], unique=False)
    op.create_table('trainer_evaluations',
    sa.Column('training_program_id', sa.String(length=36), nullable=False, comment='Training program ID'),
    sa.Column('employee_id', sa.String(length=36), nullable=False, comment='Employee ID'),
    sa.Column('trainer_id', sa.String(length=36), nullable=False, comment='Trainer user ID'),
    sa.Column('understanding_level', sa.String(length=30), nullable=True, comment='Poor, Average, Good, Excellent'),
    sa.Column('participation_level', sa.String(length=30), nullable=True, comment='Low, Moderate, High'),
    sa.Column('practical_performance', sa.String(length=30), nullable=True, comment='Needs Improvement, Satisfactory, Outstanding'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='Employee strengths'),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True, comment='Areas for improvement'),
    sa.Column('comments', sa.Text(), nullable=True, comment='Additional trainer comments'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_program_id', 'employee_id', name='uq_eval_program_emp')
    )
    op.create_index('ix_trainer_evaluations_employee_id', 'trainer_evaluations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_trainer_evaluations_id'), 'trainer_evaluations', ['id'], unique=False)
    op.create_table('assignment_submissions',
    sa.Column('assignment_id', sa.String(length=36), nullable=False, comment='Foreign key to assignment'),
    sa.Column('employee_id', sa.String(length=36), nullable=False, comment='Foreign key to employee'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Path to submitted file or document'),
    sa.Column('comments', sa.Text(), nullable=True, comment='Employee comments on submission'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='Status: Pending, Submitted, Under Review, Passed, Needs Improvement'),
    sa.Column('score', sa.Float(), nullable=True, comment='Score awarded by trainer'),
    sa.Column('trainer_feedback', sa.Text(), nullable=True, comment='Feedback from trainer'),
    sa.Column('graded_by_id', sa.String(length=36), nullable=True, comment='Trainer user ID who graded'),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when graded'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'employee_id', name='uq_submission_assign_emp')
    )
    op.create_index('ix_assignment_submissions_assignment_id', 'assignment_submissions', ['assignment_id'], unique=False)
    op.create_index('ix_assignment_submissions_employee_id', 'assignment_submissions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_id'), 'assignment_submissions', ['id'], unique=False)
    op.create_index('ix_assignment_submissions_status', 'assignment_submissions', ['status'], unique=False)
    op.create_table('modules',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Module title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Module description'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Module order within the course'),
    sa.Column('estimated_hours', sa.Integer(), nullable=True, comment='Estimated completion hours'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Module status: Not Started, In Progress, Completed'),
    sa.Column('course_id', sa.String(length=36), nullable=False, comment='Foreign key to course'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_modules_course_id', 'modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_index('ix_modules_order_index', 'modules', ['order_index'], unique=False)
    op.create_table('assessments',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Assessment title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Assessment description'),
    sa.Column('assessment_type', sa.String(length=50), nullable=False, comment='Type: Pre-test, Post-test, Quiz, Final Exam'),
    sa.Column('training_program_id', sa.String(length=36), nullable=True, comment='Optional training program ID'),
    sa.Column('module_id', sa.String(length=36), nullable=True, comment='Optional module ID'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duration in minutes (null for untimed)'),
    sa.Column('passing_score', sa.Float(), nullable=False, comment='Passing percentage score (0-100)'),
    sa.Column('attempt_limit', sa.Integer(), nullable=False, comment='Maximum allowed attempts'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='Assessment available from'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='Assessment available until'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the assessment is active'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index('ix_assessments_module_id', 'assessments', ['module_id'], unique=False)
    op.create_index('ix_assessments_training_program_id', 'assessments', ['training_program_id'], unique=False)
    op.create_index('ix_assessments_type', 'assessments', ['assessment_type'], unique=False)
    op.create_table('enrollments',
    sa.Column('employee_id', sa.String(length=36), nullable=False, comment='Enrolled employee ID'),
    sa.Column('training_program_id', sa.String(length=36), nullable=False, comment='Training program ID'),
    sa.Column('course_id', sa.String(length=36), nullable=True, comment='Optional course ID'),
    sa.Column('module_id', sa.String(length=36), nullable=True, comment='Optional module ID'),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), nullable=False, comment='Date of enrollment'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Enrollment status: Enrolled, In Progress, Completed, Dropped, Failed'),
    sa.Column('progress_percentage', sa.Float(), nullable=False, comment='Progress percentage (0.0 to 100.0)'),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True, comment='Date when training was completed'),
    sa.Column('certificate_id', sa.String(length=36), nullable=True, comment='Issued certificate ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'training_program_id', name='uq_enrollment_emp_program')
    )
    op.create_index('ix_enrollments_employee_id', 'enrollments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index('ix_enrollments_status', 'enrollments', ['status'], unique=False)
    op.create_index('ix_enrollments_training_program_id', 'enrollments', ['training_program_id'], unique=False)
    op.create_table('learning_materials',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Material title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Material description'),
    sa.Column('material_type', sa.String(length=50), nullable=False, comment='Type: PDF, PPT, DOC, Video, Image, Link'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Storage file path or external URL'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Material version'),
    sa.Column('module_id', sa.String(length=36), nullable=False, comment='Foreign key to module'),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True, comment='User ID who uploaded the material'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_materials_id'), 'learning_materials', ['id'], unique=False)
    op.create_index('ix_learning_materials_module_id', 'learning_materials', ['module_id'], unique=False)
    op.create_index('ix_learning_materials_type', 'learning_materials', ['material_type'], unique=False)
    op.create_table('training_sessions',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Session title'),
    sa.Column('training_program_id', sa.String(length=36), nullable=False, comment='Foreign key to training program'),
    sa.Column('module_id', sa.String(length=36), nullable=True, comment='Optional module ID'),
    sa.Column('trainer_id', sa.String(length=36), nullable=True, comment='Session trainer (user ID)'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Session start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Session end time'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Physical location or meeting room'),
    sa.Column('meeting_url', sa.String(length=500), nullable=True, comment='Online meeting URL (e.g., Zoom, Teams)'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Maximum session capacity'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Session status: Scheduled, In Progress, Completed, Cancelled'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_id'), 'training_sessions', ['id'], unique=False)
    op.create_index('ix_training_sessions_start_time', 'training_sessions', ['start_time'], unique=False)
    op.create_index('ix_training_sessions_status', 'training_sessions', ['status'], unique=False)
    op.create_index('ix_training_sessions_training_program_id', 'training_sessions', ['training_program_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('assessment_id', sa.String(length=36), nullable=False, comment='Foreign key to assessment'),
    sa.Column('employee_id', sa.String(length=36), nullable=False, comment='Foreign key to employee'),
    sa.Column('attempt_number', sa.Integer(), nullable=False, comment='Attempt sequence number'),
    sa.Column('score', sa.Float(), nullable=False, comment='Achieved score'),
    sa.Column('max_score', sa.Float(), nullable=False, comment='Maximum possible score'),
    sa.Column('percentage', sa.Float(), nullable=False, comment='Percentage score (0-100)'),
    sa.Column('passed', sa.Boolean(), nullable=False, comment='Whether the attempt passed'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Attempt start time'),
    sa.Column('submit_time', sa.DateTime(timezone=True), nullable=True, comment='Attempt submission time'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: In Progress, Submitted, Graded'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_attempts_assessment_id', 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_attempts_employee_id', 'assessment_attempts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_id'), 'assessment_attempts', ['id'], unique=False)
    op.create_index('ix_assessment_attempts_passed', 'assessment_attempts', ['passed'], unique=False)
    op.create_table('attendance',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='Training session ID'),
    sa.Column('employee_id', sa.String(length=36), nullable=False, comment='Employee ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Attendance status: Present, Absent, Late, Excused'),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True, comment='Actual check-in time'),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True, comment='Actual check-out time'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='Attendance notes (e.g., reason for absence)'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'employee_id', name='uq_attendance_session_emp')
    )
    op.create_index('ix_attendance_employee_id', 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index('ix_attendance_session_id', 'attendance', ['session_id'], unique=False)
    op.create_index('ix_attendance_status', 'attendance', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('assessment_id', sa.String(length=36), nullable=False, comment='Foreign key to assessment'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='The question text'),
    sa.Column('question_type', sa.String(length=50), nullable=False, comment='Type: Multiple Choice, True/False, Multiple Answer, Short Answer'),
    sa.Column('options', sa.JSON(), nullable=True, comment='JSON list of options for multiple choice questions'),
    sa.Column('correct_answer', sa.Text(), nullable=False, comment='Correct answer(s)'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='Explanation for the correct answer'),
    sa.Column('points', sa.Float(), nullable=False, comment='Points awarded for correct answer'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Order within assessment'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_assessment_id', 'questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('answers',
    sa.Column('attempt_id', sa.String(length=36), nullable=False, comment='Foreign key to assessment attempt'),
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='Foreign key to question'),
    sa.Column('selected_answer', sa.Text(), nullable=True, comment="Employee's selected/provided answer"),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='Whether the answer is correct'),
    sa.Column('points_awarded', sa.Float(), nullable=False, comment='Points awarded for this answer'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answer_attempt_question')
    )
    op.create_index('ix_answers_attempt_id', 'answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_index('ix_answers_attempt_id', table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index('ix_questions_assessment_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_attendance_status', table_name='attendance')
    op.drop_index('ix_attendance_session_id', table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index('ix_attendance_employee_id', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_assessment_attempts_passed', table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_id'), table_name='assessment_attempts')
    op.drop_index('ix_assessment_attempts_employee_id', table_name='assessment_attempts')
    op.drop_index('ix_assessment_attempts_assessment_id', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index('ix_training_sessions_training_program_id', table_name='training_sessions')
    op.drop_index('ix_training_sessions_status', table_name='training_sessions')
    op.drop_index('ix_training_sessions_start_time', table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index('ix_learning_materials_type', table_name='learning_materials')
    op.drop_index('ix_learning_materials_module_id', table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_id'), table_name='learning_materials')
    op.drop_table('learning_materials')
    op.drop_index('ix_enrollments_training_program_id', table_name='enrollments')
    op.drop_index('ix_enrollments_status', table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index('ix_enrollments_employee_id', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_assessments_type', table_name='assessments')
    op.drop_index('ix_assessments_training_program_id', table_name='assessments')
    op.drop_index('ix_assessments_module_id', table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('ix_modules_order_index', table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index('ix_modules_course_id', table_name='modules')
    op.drop_table('modules')
    op.drop_index('ix_assignment_submissions_status', table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_id'), table_name='assignment_submissions')
    op.drop_index('ix_assignment_submissions_employee_id', table_name='assignment_submissions')
    op.drop_index('ix_assignment_submissions_assignment_id', table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    op.drop_index(op.f('ix_trainer_evaluations_id'), table_name='trainer_evaluations')
    op.drop_index('ix_trainer_evaluations_employee_id', table_name='trainer_evaluations')
    op.drop_table('trainer_evaluations')
    op.drop_index('ix_feedbacks_training_program_id', table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index('ix_courses_training_program_id', table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_certificates_training_program_id', table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index('ix_certificates_employee_id', table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_assignments_training_program_id', table_name='assignments')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('user_role')
    op.drop_index('ix_training_programs_status', table_name='training_programs')
    op.drop_index(op.f('ix_training_programs_id'), table_name='training_programs')
    op.drop_index('ix_training_programs_department_id', table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_table('role_permission')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_employees_manager_id', table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index('ix_employees_department_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
